/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
//
// Created by alex on 2021/1/14
//

#ifndef _Included_me_alex_serialporthelper_SerialPortJNI
#define _Included_me_alex_serialporthelper_SerialPortJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_alex_serialporthelper_SerialPortJNI
 * Method:    openPort
 * Signature: (Ljava/lang/String;IIICI)I
 */
JNIEXPORT jint JNICALL
Java_me_alex_serialporthelper_SerialPortJNI_openPort(JNIEnv *, jobject, jstring, jint, jint, jint,
                                                     jchar);

/*
 * Class:     me_alex_serialporthelper_SerialPortJNI
 * Method:    readPort
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_me_alex_serialporthelper_SerialPortJNI_readPort(JNIEnv *, jobject, jint);

/*
 * Class:     me_alex_serialporthelper_SerialPortJNI
 * Method:    writePort
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL
Java_me_alex_serialporthelper_SerialPortJNI_writePort(JNIEnv *, jobject, jbyteArray);

/*
 * Class:     me_alex_serialporthelper_SerialPortJNI
 * Method:    setMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL
Java_me_alex_serialporthelper_SerialPortJNI_setMode(JNIEnv *, jobject, jint);


/*
 * Class:     me_alex_serialporthelper_SerialPortJNI
 * Method:    closePort
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_alex_serialporthelper_SerialPortJNI_closePort(JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_me_alex_serialporthelper_SerialPortJNI_finalize(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif